# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/rtf-to-pdf:latest .
        docker build -t ${{ secrets.DOCKER_USERNAME }}/rtf-to-pdf:1.0.${{ github.run_number }} .
        
    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/rtf-to-pdf:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/rtf-to-pdf:1.0.${{ github.run_number }}
